services:
  car-rental-apps:
    build: .
    container_name: car-rental-app
    environment:
      DB_HOST: postgres
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - car-rental-app-network

  postgres:
    image: postgres
    container_name: car-rental-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - "5432:5432"
    volumes:
      - car-rental-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - car-rental-app-network



volumes:
  car-rental-db:


networks:
  car-rental-app-network:
    driver: bridge
